let number = 4;
let string = "Rhabarber";
let lecker = true; //boolean

console.log(number)
console.log(string)
console.log(lecker)


//Berechnen
let number1 = 40;
let number2 = 20;
console.log(number1 + number2);



//++ ist dasselbe wie number1 = number1 + 1


let firstName = "Liza";
let lastName = "Morelli";

let fullName = firstName + " " + lastName;
console.log(fullName);





console.log(5 == "5")
console.log(5 > 10)


function functionName(zahl1, zahl2) {
    let result = zahl1 + zahl2;
    return result;
}

console.log(functionName(5, 10));
